server:
  port: 9002
spring:
  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
security:
  basic:
    enable: false
logging:
  level:
    org:
      springframework:
        web: debug

